services:
  web: 
    build:
      context: .
    environment:
      - TOURNAMENT_NAME=${TOURNAMENT_NAME}
      - PROBLEM_PATH=/problem/${PROBLEM_FILE}
      - INITIAL_SCORE=${INITIAL_SCORE}
      - PROBLEM_CLASS=${PROBLEM_CLASS}
      - PROBLEM_MAXIMIZE=${PROBLEM_MAXIMIZE}
      - ROOT_FOLDER_ID=${ROOT_FOLDER_ID}
      - GOOGLE_CREDENTIALS_PATH=/credentials/${GOOGLE_CREDENTIALS_FILE}
      - SNAPSHOT_FOLDER_PATH=/snapshots
      - TIMEZONE=${TIMEZONE}
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT}
    stop_signal: SIGINT
    volumes:
      - ./${PROBLEM_FILE}:/problem/${PROBLEM_FILE}:ro
      - ./${GOOGLE_CREDENTIALS_FILE}:/credentials/${GOOGLE_CREDENTIALS_FILE}:ro
      - ${SNAPSHOT_FOLDER_PATH}:/snapshots
    ports:
      - '${FLASK_PORT}:8080'